# 容器 配置
server:
  port: 8080
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 数据库 及 Redis 配置    
spring:
  redis:
    host: localhost
    port: 6379
    password: 
  datasource:
    url: jdbc:mysql://localhost:3306/video?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10
  mail:
    host: smtp.qq.com
    username: 1486887838@qq.com
    password: foysiydebqoghabg
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false
          required: false

# Mybatis 配置
mybatis:
  config-location: classpath:/mybatis.xml

# Redis Key 前缀
redis:
  prefix:
    signUp: SIGN

# 本站信息
app:
  name: smallcc
  domain: smallcc.cn
